### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by Anonymous941** [nfcim/nfsee#27]
When trying to compile:

```plain
Resolving dependencies... 
Note: intl is pinned to version 0.19.0 by flutter_localizations from the flutter SDK.
See https://dart.dev/go/sdk-version-pinning for details.


Because nfsee depends on flutter_localizations from sdk which depends on intl 0.19.0, intl 0.19.0 is required.
So, because nfsee depends on intl ^0.18.1, version solving failed.


You can try the following suggestion to make the pubspec resolve:
* Try upgrading your constraint on intl: flutter pub add intl:^0.19.0
```

If I follow the suggestion, it fails with a different error:

```plain
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_nfc_kit:compileReleaseKotlin'.
> Inconsistent JVM-target compatibility detected for tasks 'compileReleaseJavaWithJavac' (17) and 'compileReleaseKotlin' (21).

  Consider using JVM Toolchain: https://kotl.in/gradle/jvm/toolchain
  Learn more about JVM-target validation: https://kotl.in/gradle/jvm/target-validation 

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 1s
Running Gradle task 'assembleRelease'...                         1,790ms
Gradle task assembleRelease failed with exit code 1
```

**Comment by jiegec** [comment]
Fixed.

**Comment by Anonymous941** [comment]
@jiegec Still not working unfortunately.  I'm using the flutter version in the submodule
```plain
Warning: SDK processing. This version only understands SDK XML versions up to 3 but an SDK XML file of version 4 was encountered. This can happen if you use versions of Android Studio and the command-line tools that were released at different times.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_nfc_kit:compileReleaseKotlin'.
> Inconsistent JVM-target compatibility detected for tasks 'compileReleaseJavaWithJavac' (17) and 'compileReleaseKotlin' (21).

  Consider using JVM Toolchain: https://kotl.in/gradle/jvm/toolchain
  Learn more about JVM-target validation: https://kotl.in/gradle/jvm/target-validation 

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 20s
Running Gradle task 'assembleRelease'...                           20.5s
Gradle task assembleRelease failed with exit code 1
```

**Comment by jiegec** [comment]
> @jiegec Still not working unfortunately. I'm using the flutter version in the submodule
> 
> ```
> Warning: SDK processing. This version only understands SDK XML versions up to 3 but an SDK XML file of version 4 was encountered. This can happen if you use versions of Android Studio and the command-line tools that were released at different times.
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':flutter_nfc_kit:compileReleaseKotlin'.
> > Inconsistent JVM-target compatibility detected for tasks 'compileReleaseJavaWithJavac' (17) and 'compileReleaseKotlin' (21).
> 
>   Consider using JVM Toolchain: https://kotl.in/gradle/jvm/toolchain
>   Learn more about JVM-target validation: https://kotl.in/gradle/jvm/target-validation 
> 
> * Try:
> > Run with --stacktrace option to get the stack trace.
> > Run with --info or --debug option to get more log output.
> > Run with --scan to get full insights.
> > Get more help at https://help.gradle.org.
> 
> BUILD FAILED in 20s
> Running Gradle task 'assembleRelease'...                           20.5s
> Gradle task assembleRelease failed with exit code 1
> ```



> @jiegec Still not working unfortunately. I'm using the flutter version in the submodule
> 
> ```
> Warning: SDK processing. This version only understands SDK XML versions up to 3 but an SDK XML file of version 4 was encountered. This can happen if you use versions of Android Studio and the command-line tools that were released at different times.
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':flutter_nfc_kit:compileReleaseKotlin'.
> > Inconsistent JVM-target compatibility detected for tasks 'compileReleaseJavaWithJavac' (17) and 'compileReleaseKotlin' (21).
> 
>   Consider using JVM Toolchain: https://kotl.in/gradle/jvm/toolchain
>   Learn more about JVM-target validation: https://kotl.in/gradle/jvm/target-validation 
> 
> * Try:
> > Run with --stacktrace option to get the stack trace.
> > Run with --info or --debug option to get more log output.
> > Run with --scan to get full insights.
> > Get more help at https://help.gradle.org.
> 
> BUILD FAILED in 20s
> Running Gradle task 'assembleRelease'...                           20.5s
> Gradle task assembleRelease failed with exit code 1
> ```

Maybe try something like https://github.com/skiptools/skip/issues/150#issuecomment-2183371302

**Comment by Anonymous941** [comment]
> Maybe try something like [skiptools/skip#150 (comment)](https://github.com/skiptools/skip/issues/150#issuecomment-2183371302)

Then I get this error:

```plain
1: Task failed with an exception.
-----------
* Where:
Build file '/.../nfsee/android/app/build.gradle' line: 86

* What went wrong:
A problem occurred evaluating project ':app'.
> Could not get unknown property 'libs' for object of type org.jetbrains.kotlin.gradle.plugin.KotlinAndroidPlugin$apply$1$1$kotlinOptions$1.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
==============================================================================

2: Task failed with an exception.
-----------
* Where:
Build file '/.../nfsee/android/app/build.gradle' line: 86

* What went wrong:
A problem occurred evaluating project ':app'.
> Could not get unknown property 'libs' for object of type org.jetbrains.kotlin.gradle.plugin.KotlinAndroidPlugin$apply$1$1$kotlinOptions$1.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
==============================================================================

BUILD FAILED in 8s
Running Gradle task 'assembleRelease'...                            8.8s
Gradle task assembleRelease failed with exit code 1
```

**Comment by jiegec** [comment]
> Strange that it's working for you but not me, what version of flutter are you using? I'm using 3.19.5, which is what's in the `.flutter` submodule

The submodule has been updated to 3.24.5

**Comment by jiegec** [comment]
Try some thing like:

```
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

   kotlinOptions {
        jvmTarget = '17'
    }
```

**Comment by Anonymous941** [comment]
That doesn't change anything.  Is `android/app/build.gradle` the right file?

**Comment by jiegec** [comment]
> That doesn't change anything, I still get the same error `Inconsistent JVM-target compatibility detected for tasks 'compileReleaseJavaWithJavac' (17) and 'compileReleaseKotlin' (21).`. Is `android/app/build.gradle` the right file?

Sorry but I still can't reproduce your problem. It also successfully compiles in GitHub Actions.

**Comment by Anonymous941** [comment]
I _finally_ fixed this.  It turns out that simply having Java 21 installed caused the issue, and for some reason flutter didn't attempt to use Java 17 even though I had it installed

Running `sudo update-alternatives --config java` let me choose Java 17, and it finally compiled.  Thank you for trying to help me with this
